import assert from "node:assert/strict";
import {createBlankEmpireTodo,isEmpireTodoComplete} from "../src/components/notes/empireTodoModel.ts";
const task=createBlankEmpireTodo(new Date("2026-08-15T13:00:00Z"));
assert.equal(task.status,"Backlog");
assert.equal(task.createdAt,"2026-08-15T13:00:00.000Z");
assert.equal(task.progress,undefined);
assert.equal(task.projectKeys,undefined);
assert.equal(isEmpireTodoComplete({...task,status:"Complete"}),true);
assert.equal(isEmpireTodoComplete(task),false);
console.log("Task creation and authoritative completion verified; unified view and draft behavior have dedicated tests.");
