import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const source = await readFile(new URL("../scripts/tauri_e2e.mjs", import.meta.url), "utf8");
const devLauncherSource = await readFile(new URL("../scripts/tauri_dev.mjs", import.meta.url), "utf8");
assert.match(source, /mkdtemp\(/);
assert.match(source, /prepareIsolatedO2Root/);
assert.match(source, /O2_E2E_HOME: fixture\.e2eHome/);
assert.match(source, /createdProjectRepo/);
assert.match(source, /tab-agents/);
assert.match(source, /AGENT ROSTER/);
assert.match(source, /modal-create-agent/);
assert.match(source, /agentProfileDir/);
assert.match(source, /agentNotesPath/);
assert.match(source, /create governed Agent profile inside the isolated root/);
assert.match(source, /persist Agent autosave into the isolated O2 root/);
assert.match(source, /tab-infrastructure/);
assert.match(source, /modal-create-infrastructure/);
assert.match(source, /infrastructureRecordDir/);
assert.match(source, /infrastructureNotesPath/);
assert.match(source, /create governed Infrastructure record inside the isolated root/);
assert.match(source, /persist Infrastructure autosave into the isolated O2 root/);
assert.match(source, /modal-project-repo/);
assert.match(source, /apply the isolated governed project root/);
assert.match(source, /build a project entirely inside the isolated root/);
assert.match(source, /detached: true/);
assert.match(source, /process\.kill\(-child\.pid, signal\)/);
assert.match(source, /fixture\.o2Root/);
assert.match(source, /\$\{fixtureKey\}\.stop/);
assert.match(source, /rm\(fixture\.tempRoot, \{ recursive: true, force: true \}\)/);
assert.match(source, /\[e2e\] passed: isolated tab switching, Agent and Infrastructure creation, governed-note autosave, project bootstrap, and runtime lifecycle/);
assert.doesNotMatch(source, /O2_ROOT: "\/home\/chris\/dev\/o2"/);
assert.doesNotMatch(source, /const driverPort = 4447/);
assert.match(devLauncherSource, /function waitForChild/);
assert.match(devLauncherSource, /await runTauri\(repoRoot\)/);
assert.match(devLauncherSource, /await runTauri\(repoRoot, vite\)/);
assert.match(devLauncherSource, /ownedVite\.kill\("SIGTERM"\)/);
console.log("tauri e2e isolation contract: ok");
