import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const source = await readFile(new URL("../scripts/tauri_e2e.mjs", import.meta.url), "utf8");
const isolation = await readFile(new URL("../scripts/native_acceptance_lib.mjs", import.meta.url), "utf8");
const productionProbe = await readFile(new URL("../scripts/tauri_production_readonly.mjs", import.meta.url), "utf8");
const devLauncherSource = await readFile(new URL("../scripts/tauri_dev.mjs", import.meta.url), "utf8");
const packageJson = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
assert.equal(packageJson.scripts["test:tauri-e2e"], "npx tauri build --debug --no-bundle && node scripts/tauri_e2e.mjs");
assert.equal(packageJson.scripts["test:tauri-production-readonly"], "node scripts/tauri_production_readonly.mjs");
assert.match(source, /mkdtemp\(/);
assert.match(source, /prepareIsolatedO2Root/);
assert.match(source, /target\/debug\/radcontrol-app/);
assert.match(source, /assertWritableFixtureIsolation\(fixture\)/);
assert.match(source, /assertInstalledO2Unchanged\(installedBefore\)/);
assert.match(source, /createBubblewrapApplication/);
assert.match(source, /attest isolated native runtime before writable interaction/);
assert.match(source, /project-archetypes\.json/);
assert.match(source, /retired: false/);
assert.match(source, /cp\(path\.join\(o2Root, "registry", "empire-todo-seeds\.json"\), empireTodoPath\)/);
assert.match(source, /mkdir\(e2eHome, \{ recursive: true \}\)/);
assert.match(source, /O2_E2E_HOME: fixture\.e2eHome/);
assert.match(source, /XDG_CACHE_HOME: fixture\.xdgCacheHome/);
assert.match(source, /XDG_CONFIG_HOME: fixture\.xdgConfigHome/);
assert.match(source, /XDG_DATA_HOME: fixture\.xdgDataHome/);
assert.match(source, /createdProjectRepo/);
assert.match(source, /tab-agents/);
assert.match(source, /AGENT ROSTER/);
assert.match(source, /modal-create-agent/);
assert.match(source, /agentProfileDir/);
assert.match(source, /agentNotesPath/);
assert.match(source, /create governed Agent profile inside the isolated root/);
assert.match(source, /persist Agent autosave into the isolated O2 root/);
assert.match(source, /tab-infrastructure/);
assert.match(source, /modal-create-infrastructure/);
assert.match(source, /infrastructureRecordDir/);
assert.match(source, /infrastructureNotesPath/);
assert.match(source, /create governed Infrastructure record inside the isolated root/);
assert.match(source, /persist Infrastructure autosave into the isolated O2 root/);
assert.match(source, /notes-mode-empire_blueprint/);
assert.match(source, /notes-mode-o2_knowledge/);
assert.match(source, /my-notes-input/);
assert.match(source, /radcontrol-operator/, "E2E must prove private scratchpad state");
assert.match(source, /render read-only O2 Knowledge overview/);
assert.match(source, /notes-mode-empire_todo/);
assert.match(source, /activateCompletionCheckbox/);
assert.match(source, /dom-click/);
assert.match(source, /Complete without Timeline/);
assert.match(source, /Add to Timeline creates one bounded milestone/);
assert.match(source, /empire-todo-completed-view/);
assert.match(source, /dqotd-dinosaur-content/);
assert.match(source, /restart isolated RadControl/);
assert.match(source, /reload completed Empire To-Do item after native restart/);
assert.match(source, /docs", "portfolio/);
assert.match(source, /tab-legal/);
assert.match(source, /legal-ownership-diagram/);
assert.match(source, /legal-portal-access-diagram|OPERATING ACCESS — NOT OWNERSHIP/);
assert.match(source, /RadWolfe must not render inside the Radcon ownership lane/);
assert.match(source, /Offroad Croquet must render beneath Radcon Enterprises/);
assert.match(source, /Legal normal text must remain readable/);
assert.match(source, /render the legal ownership diagram responsively/);
assert.match(source, /legal-mode-formation/);
assert.match(source, /legal-mode-addresses/);
assert.match(source, /legal-mode-brands/);
assert.match(source, /legal-mode-accounts/);
assert.match(source, /legal-mode-documents/);
assert.match(source, /preserve governed Legal archives/);
assert.match(source, /tab-sentinel/);
assert.match(source, /sentinel-health-check/);
assert.match(source, /DURABLE FRESHNESS/);
assert.match(source, /ADVANCED SYSTEM INFORMATION/);
assert.match(source, /QUICK ANSWERS/);
assert.match(source, /No recorded anomaly/);
assert.match(source, /security-mode-security_guardian/);
assert.match(source, /security-guardian-check/);
assert.match(source, /security-mode-empire_operations/);
assert.match(source, /guardian-activity-row/);
assert.match(source, /System76 Workstation/);
assert.match(source, /RADCONTROL_E2E_SCREENSHOT_PATH/);
assert.match(source, /modal-project-repo/);
assert.match(source, /apply the isolated governed project root/);
assert.match(source, /modal-project-purpose/);
assert.match(source, /modal-project-users/);
assert.match(source, /modal-project-problem/);
assert.match(source, /modal-project-value/);
assert.match(source, /modal-project-success/);
assert.match(source, /modal-review-project/);
assert.match(source, /render the O2 Project Intent review/);
assert.match(source, /build a project entirely inside the isolated root/);
assert.match(source, /detached: true/);
assert.match(source, /process\.kill\(-child\.pid, signal\)/);
assert.match(source, /fixture\.o2Root/);
assert.match(source, /rm\(fixture\.tempRoot, \{ recursive: true, force: true \}\)/);
assert.match(source, /\[e2e\] passed:/);
assert.doesNotMatch(source, /O2_ROOT: "\/home\/chris\/dev\/o2"/);
assert.doesNotMatch(source, /const driverPort = 4447/);
assert.match(isolation, /installed O2 cannot be the writable E2E fixture/);
assert.match(isolation, /must not resolve through a symlink/);
assert.match(isolation, /fixture Empire To-Do seed is missing or unexpected/);
assert.match(isolation, /native writable artifact did not consume the preflighted O2 root/);
assert.match(productionProbe, /production-artifact-read-only/);
assert.match(productionProbe, /createBubblewrapApplication/);
assert.doesNotMatch(productionProbe, /empire\.todo\.save|files\.write|files\.rename|project_create\.(?:start|bootstrap)/);
assert.match(devLauncherSource, /function waitForChild/);
assert.match(devLauncherSource, /await runTauri\(repoRoot\)/);
assert.match(devLauncherSource, /await runTauri\(repoRoot, vite\)/);
assert.match(devLauncherSource, /ownedVite\.kill\("SIGTERM"\)/);
console.log("tauri e2e isolation contract: ok");
