import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const config = JSON.parse(await readFile(new URL("../src-tauri/tauri.conf.json", import.meta.url)));
const capability = JSON.parse(await readFile(new URL("../src-tauri/capabilities/default.json", import.meta.url)));

assert.equal(config.app.withGlobalTauri, false);
assert.match(config.app.security.csp, /default-src 'self'/);
assert.doesNotMatch(config.app.security.csp, /\x27unsafe-eval\x27/);
assert.deepEqual(capability.permissions, ["core:default"]);
assert.doesNotMatch(JSON.stringify(capability.permissions), /reveal|shell:|fs:|clipboard/);
const bridge = await readFile(new URL("../src-tauri/src/commands/o2.rs", import.meta.url), "utf8");
const processBoundary = await readFile(new URL("../src-tauri/src/commands/o2_process.rs", import.meta.url), "utf8");
assert.match(bridge, /assert!\(ProjectAction::parse\("commit"\)\.is_none\(\)\)/);
assert.doesNotMatch(bridge, /"kill_port\."/);
assert.match(bridge, /"contract_info"/);
assert.match(bridge, /"router\.health"/);
assert.match(bridge, /"empire\.map"/);
assert.match(bridge, /"empire\.sweep"/);
assert.match(bridge, /"stop"/);
assert.match(bridge, /enum ProjectAction/);
assert.match(bridge, /Self::Dev \| Self::DevStrict \| Self::Stop/);
assert.match(bridge, /fn payload_spec/);
assert.match(bridge, /"files.write" => \("files.write.stdin"/);
assert.match(bridge, /"empire.todo.save" =>/);
assert.match(bridge, /"empire.todo.save.stdin"/);
assert.match(bridge, /"sentinel.status"/);
assert.match(bridge, /"radcontrol.golden_state"/);
assert.match(bridge, /"sentinel.host.current"/);
assert.match(bridge, /"sentinel.host.deep_check"/);
assert.match(bridge, /"sentinel.host.investigate."/);
assert.match(bridge, /"sentinel.ask."/);
assert.match(bridge, /"workstation.updates.check"/);
assert.match(bridge, /"project_create.preview."/);
assert.match(bridge, /"project-create.preview"[\s\S]*?TimeoutClass::Extended,[\s\S]*?None/);
assert.doesNotMatch(bridge, /"sentinel.action.dry_run."/);
assert.doesNotMatch(bridge, /"workstation.cleanup.apply"/);
assert.match(bridge, /"workstation.cleanup.pop_upgrade.preview"/);
assert.match(bridge, /"workstation.cleanup.pop_upgrade.apply"/);
assert.doesNotMatch(bridge, /"workstation.updates.refresh"/);
assert.doesNotMatch(bridge, /shell\(true\)/);
assert.doesNotMatch(bridge, /files\.new"\)/);
assert.doesNotMatch(bridge, /Command::new\("bash"\)|Command::new\("git"\)/);
assert.match(bridge, /const BASH_EXECUTABLE: &str = "\/usr\/bin\/bash"/);
assert.match(bridge, /const GIT_EXECUTABLE: &str = "\/usr\/bin\/git"/);
assert.match(bridge, /const CONCURRENT_INVOCATION_LIMIT: usize = 4/);
assert.match(bridge, /BridgeFailureKind::AuditFailure/);
assert.match(bridge, /redact_sensitive_text\(&outcome\.stdout\)/);
assert.match(bridge, /redact_sensitive_text\(&outcome\.stderr\)/);
assert.match(bridge, /const RUNTIME_HOME: &str = "\/home\/chris"/);
assert.match(bridge, /ensure_private_directory\(&bridge_state\.join\("tmp"\)\)/);
assert.match(processBoundary, /\.env_clear\(\)/);
assert.match(processBoundary, /\.env\("TMPDIR", temp_dir\)/);
assert.match(processBoundary, /\.process_group\(0\)/);
assert.match(processBoundary, /libc::SIGTERM/);
assert.match(processBoundary, /libc::SIGKILL/);
assert.match(processBoundary, /pub fn terminate_active_processes/);
assert.match(bridge, /pub\(crate\) fn e2e_mode\(\) -> bool/);
assert.match(bridge, /if e2e_mode\(\) \{/);
assert.match(bridge, /pub fn e2e_project_roots\(\) -> Option<E2EProjectRoots>/);
assert.match(bridge, /std::env::var\("O2_E2E_HOME"\)\.map_err/);
const app = await readFile(new URL("../src-tauri/src/lib.rs", import.meta.url), "utf8");
const opener = await readFile(new URL("../src-tauri/src/commands/opener.rs", import.meta.url), "utf8");
const governedOpener = await readFile(new URL("../src/components/common/governedOpener.ts", import.meta.url), "utf8");
assert.match(app, /if commands::o2::e2e_mode\(\)/);
assert.doesNotMatch(app, /std::env::var\("RADCONTROL_E2E"\)/);
assert.match(app, /commands::o2::terminate_active_processes\(\)/);
assert.match(app, /open_js_links_on_click\(false\)/);
assert.match(app, /commands::opener::open_governed_url/);
assert.doesNotMatch(app, /clipboard_manager/);
assert.match(opener, /const PROVIDER_HOSTS/);
assert.match(opener, /URL_DENIED/);
assert.match(opener, /matches!\(host, "localhost" \| "127\.0\.0\.1"\)/);
assert.match(opener, /project\.port == Some\(port\)/);
assert.match(opener, /candidate_url == parsed/);
assert.doesNotMatch(governedOpener, /@tauri-apps\/plugin-opener|window\.open/);
assert.match(governedOpener, /invoke<string>\("open_governed_url"/);
const cargo = await readFile(new URL("../src-tauri/Cargo.toml", import.meta.url), "utf8");
assert.doesNotMatch(cargo, /tauri-plugin-clipboard-manager|chrono/);
assert.match(cargo, /serde_json = "1"/);
assert.match(cargo, /libc = "0\.2"/);
assert.match(cargo, /regex = "1"/);
assert.match(cargo, /url = "2"/);
console.log("project action allowlist: commit excluded");
console.log("tauri security contract: ok");
