import { useCallback, useEffect, useRef, useState } from "react";
import { readO2File, writeO2File } from "../common/o2Files";
const PATH = "docs/radcontrol/empire_blueprint/empire_blueprint_20260822.md";
type Props = { registerBeforeTabChangeSaver?: (fn: (() => Promise<boolean>) | null) => void };
export function BlueprintWorkspace({ registerBeforeTabChangeSaver }: Props) {
 const [content, setContent] = useState(""); const [editing, setEditing] = useState(false); const [status, setStatus] = useState("Loading…"); const [error, setError] = useState(""); const dirty = useRef(false); const value = useRef("");
 useEffect(() => { void readO2File(PATH).then((result) => { setContent(result.content || ""); value.current = result.content || ""; setStatus("Current"); }).catch((reason) => { setError(reason instanceof Error ? reason.message : String(reason)); setStatus("Unavailable"); }); }, []);
 const save = useCallback(async () => { if (!dirty.current) return true; setStatus("Saving…"); try { await writeO2File({ path: PATH, content: value.current }); dirty.current = false; setStatus("Saved"); return true; } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); setStatus("Not saved"); return false; } }, []);
 useEffect(() => { registerBeforeTabChangeSaver?.(save); return () => registerBeforeTabChangeSaver?.(null); }, [registerBeforeTabChangeSaver, save]);
 return <section className="blueprintShell" data-testid="empire-blueprint-workspace"><div className="scratchpadHeading"><div><strong>EMPIRE BLUEPRINT</strong><span>One living owner’s manual · O2-owned reference, not a collection</span></div><div><small>{status}</small><button className="btn btnGhost btnCompact" type="button" onClick={() => { if (editing) void save(); setEditing(!editing); }}>{editing ? "Finish editing" : "Edit intentionally"}</button></div></div>{error ? <div className="panelError">{error}</div> : null}{editing ? <textarea className="scratchpadArea blueprintEditor" value={content} onChange={(event) => { setContent(event.target.value); value.current = event.target.value; dirty.current = true; setStatus("Unsaved changes"); }} onBlur={() => void save()} /> : <article className="blueprintArticle">{content.split("\n").map((line, index) => line.startsWith("# ") ? <h1 key={index}>{line.slice(2)}</h1> : line.startsWith("## ") ? <h2 key={index}>{line.slice(3)}</h2> : line.startsWith("- ") ? <li key={index}>{line.slice(2)}</li> : line ? <p key={index}>{line}</p> : null)}</article>}</section>;
}
